### ISSUE TITLE
Emulator integration

### ISSUE THREAD

**Issue by bigwhitebuddha** [LemmusLemmus/GlosSI-Integration-Playnite#6] opened 2022-08-15 21:35 UTC
I can't seem to find a way to add emulators to GlosSI via this playnite extension.

**Comment by LemmusLemmus** [comment] 2022-08-16 12:28
Could you describe in more detail what the problem is? It should be possible to add emulated games the same way other games are added, i.e. by selecting them and clicking "Add Integration".
Are you getting any error messages? If you are getting the error message below (caused by games lacking an icon), the bug should be fixed in the latest release (v1.0.2).
> GlosSI Integration failed to add the GlosSI target configuration file and/or Steam shortcut for "game", the adding process was aborted: Value cannot be null.
Parameter name: source

Or are you trying to add all games associated with an emulator as a single GlosSI shortcut? This is currently not possible, but such a feature could definitely be added.

**Comment by bigwhitebuddha** [comment] 2022-08-16 21:28
The 1.02 version has resolved this issue. 

I was running on 1.01 when this issue was encountered. It showed the exact error you mentioned earlier. 

I have tested the 1.02 version on a number of emulated games, and it works perfectly!

**Comment by LemmusLemmus** [comment] 2022-08-17 06:51
Thanks for noticing and reporting the issue!

**Closed as completed** 2022-08-17 06:51 UTC
