### ISSUE TITLE
Shortcut doesn't fill the Path and Launch Arguments

### ISSUE THREAD

**Issue by tymondouglas** [LemmusLemmus/GlosSI-Integration-Playnite#24] opened 2023-06-30 13:48 UTC
Self-explanatory, but every time i add a new shortcut through PlayNite / GlosSI-Integration, it creates an empty target in Glossi, resulting in it only launching Glossi-target instead of launching the game.
Picture related: Shortcut created through integration
![image](https://github.com/LemmusLemmus/GlosSI-Integration-Playnite/assets/84814396/7924a0d9-08f3-4c17-be1d-e9b7ea4558ec)

Target JSON:
```
{
    "controller": {
        "allowDesktopConfig": false,
        "emulateDS4": false,
        "maxControllers": 4
    },
    "devices": {
        "hideDevices": true,
        "realDeviceIds": false
    },
    "extendedLogging": false,
    "icon": "C:\\Users\\Tymon\\AppData\\Roaming\\Playnite\\library\\files\\e6964537-8e74-4d13-8b82-bc4bf4fb2b0a\\4d756d57-babe-4516-9f96-0e6f00b4c489.png",
    "launch": {
        "closeOnExit": false,
        "ignoreLauncher": true,
        "killLauncher": false,
        "launch": false,
        "launchAppArgs": null,
        "launchPath": null,
        "launcherProcesses": [
        ],
        "waitForChildProcs": false
    },
    "name": "Rune Factory 4 Special - Windows Edition",
    "oldName": "Rune Factory 4 Special - Windows Edition",
    "snapshotNotify": false,
    "version": 1,
    "window": {
        "disableOverlay": false,
        "maxFps": null,
        "scale": null,
        "windowMode": false
    }
}

```

**Comment by LemmusLemmus** [comment] 2023-06-30 22:33
This is currently the intended behavior. When you launch games via Playnite, Playnite will launch the game itself and the GlosSITarget shortcut will be launched as merely an overlay. As such, the game paths of the created shortcuts are empty, since Playnite does the game launching and one would not want to launch the same game twice.

It is not optimal however, since the shortcut becomes practically useless when launched from Steam. This should hopefully be resolved in the next version of the extension, by (among other things) automatically disabling and enabling game launching from GlosSITarget based on whether it was launched from Steam or the Playnite extension.

**Comment by tymondouglas** [comment] 2023-06-30 23:57
I see, thanks.
I should have specified that it only happened when launching through steam.

**Comment by LemmusLemmus** [comment] 2023-09-03 14:01
If you are interested in trying out an experimental version that adds this functionality, see https://github.com/LemmusLemmus/GlosSI-Integration-Playnite/issues/23#issuecomment-1704314198.

**Closed as completed** 2024-06-23 16:32 UTC
Labels: enhancement
